name: Build iOS
on: [workflow_call, workflow_dispatch]
jobs:
  build_ios:
    timeout-minutes: 30
    strategy:
      matrix:
        preset: ["ios-arm64-host_x64", "iphonesimulator-x64-host_x64"]
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          path: nakama-cpp
      - run: ./nakama-cpp/ci/setup-osx.sh
        shell: bash
      - uses: ./nakama-cpp/.github/actions/build-platform-and-upload
        with:
          path: nakama-cpp
          preset: ${{ matrix.preset }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
