name: Build Linux
on: [workflow_call, workflow_dispatch]
jobs:
  setup_vcpkg:
      uses: ./.github/workflows/setup_vcpkg.yml
  build_linux:
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo ./ci/setup-ubuntu.sh
        shell: bash
      - uses: ./.github/actions/cmake-build
        with:
          preset: linux-amd64
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

