name: Build iOS
on: [workflow_call, workflow_dispatch]
jobs:
  ios_matrix:
    timeout-minutes: 30
    strategy:
      matrix:
        preset: ["ios-arm64-host_x64", "iphonesimulator-x64-host_x64"]
    runs-on: macos-12
    steps:
      - run: ./ci/setup-osx.sh
        shell: bash
      - uses: ./.github/actions/setup-vcpkg
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cmake-build
        with:
          preset: ${{ matrix.preset }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}